export const GEX_ASSUMPTIONS = {
  optionUniverse: "deribit-btc-inverse-btc-settled",
  contractMultiplierBtc: 1,
  normalizedOpenInterestUnit: "BTC",
  canonicalIvUnit: "decimal",
  deribitMarkIvInputUnit: "percentage-points",
  callSign: 1,
  putSign: -1,
  exposureUnit: "USD-hedge-notional-per-1pct-move",
  formula: "sign * gamma * openInterestBtc * spotUsd^2 * 0.01",
  profileVolatilityMode: "sticky-iv-per-contract",
  profileSearchLowerMultiplier: 0.7,
  profileSearchUpperMultiplier: 1.3,
  crossingSignificanceFraction: 0.005,
  minimumProfileTimeToExpiryMs: 15 * 60 * 1_000,
  wallStrikeLowerMultiplier: 0.75,
  wallStrikeUpperMultiplier: 1.25,
  wallMinimumSameSideGrossShare: 0.01,
  wallMinimumOpenInterestBtc: 1,
  defaultExpiryScope: "less-than-or-equal-30-dte",
  maximumProfileRecomputeFrequencyMs: 2_000,
} as const;
